[pytest]
filterwarnings =
    ignore::UserWarning:paddle.utils.cpp_extension.extension_utils
    ignore::UserWarning:No ccache found
    ignore::DeprecationWarning
addopts = -v --tb=short --disable-warnings
testpaths = tests
